import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { ApiError } from '../../core/api/api-error';
import { Adjuster, AuditEvent, ClaimDetail, ClaimStatus, Recommendation } from '../../shared/models/claim.models';
import { ClaimsApiService } from '../data-access/claims-api.service';

@Component({
  standalone:true,
  imports:[CommonModule,ReactiveFormsModule,RouterLink],
  template:`
    <a routerLink="/claims">← Back to claims</a><div *ngIf="loading()" class="panel" role="status">Loading claim workspace…</div><div *ngIf="pageError()" class="alert" role="alert">{{pageError()}}</div>
    <ng-container *ngIf="claim() as item"><header class="claim-header"><div><p class="eyebrow">{{item.claimNumber}}</p><h1>{{item.claimantName}}</h1><p>{{label(item.claimType)}} · {{item.incidentDate | date:'mediumDate'}}</p></div><div class="header-badges"><span class="badge priority">{{label(item.priority)}}</span><span class="badge">{{label(item.status)}}</span></div></header>
      <div class="workspace"><div class="main-column"><section class="panel"><h2>Claim facts</h2><dl><div><dt>Claimant email</dt><dd>{{item.claimantEmail}}</dd></div><div><dt>Estimated loss</dt><dd>{{item.estimatedLoss | currency}}</dd></div><div><dt>SLA deadline</dt><dd>{{item.slaDeadline | date:'medium'}}</dd></div><div><dt>Completeness</dt><dd>{{item.completenessPercentage}}%</dd></div></dl><p>{{item.description}}</p></section>
      <section class="panel"><h2>Evidence and triage</h2><div *ngIf="item.missingEvidence.length" class="notice"><strong>Missing evidence</strong><ul><li *ngFor="let value of item.missingEvidence">{{value}}</li></ul></div><p *ngIf="!item.missingEvidence.length">All required evidence indicators are present.</p><h3>Priority factors</h3><ul><li *ngFor="let value of item.priorityFactors">{{value}}</li></ul></section>
      <section class="panel"><h2>Audit timeline</h2><div *ngIf="!audit().length" class="empty">No events recorded.</div><ol class="timeline"><li *ngFor="let event of audit()"><strong>{{event.summary}}</strong><span>{{event.actor}} · {{event.occurredAt | date:'medium'}}</span><small *ngIf="event.previousValue || event.newValue">{{event.previousValue || 'None'}} → {{event.newValue || 'None'}}</small></li></ol></section></div>
      <aside><section class="panel"><h2>Assignment</h2><select [formControl]="adjusterId"><option value="">Select adjuster</option><option *ngFor="let adjuster of adjusters()" [value]="adjuster.id">{{adjuster.displayName}}</option></select><button class="button primary" [disabled]="!adjusterId.value||acting()" (click)="assign()">Assign</button><div *ngIf="assignmentError()" class="inline-error">{{assignmentError()}}</div></section>
      <section class="panel"><h2>Status</h2><select [formControl]="nextStatus"><option value="">Select next status</option><option *ngFor="let status of item.allowedNextStatuses" [value]="status">{{label(status)}}</option></select><button class="button primary" [disabled]="!nextStatus.value||acting()" (click)="updateStatus()">Update status</button><div *ngIf="statusError()" class="inline-error">{{statusError()}}</div></section>
      <section class="panel recommendation"><h2>Decision support</h2><button *ngIf="!recommendation()" class="button primary" [disabled]="acting()" (click)="generate()">Generate recommendation</button><ng-container *ngIf="recommendation() as insight"><p class="action">{{label(insight.recommendedAction)}}</p><p>{{insight.explanation}}</p><p><strong>Confidence:</strong> {{insight.confidence}}%</p><ul><li *ngFor="let value of insight.missingInformation">{{value}}</li></ul><div *ngIf="insight.reviewState==='PENDING'" class="review-actions"><button class="button primary" [disabled]="acting()" (click)="review('APPROVED')">Approve</button><button class="button danger" [disabled]="acting()" (click)="review('REJECTED')">Reject</button></div><p *ngIf="insight.reviewState!=='PENDING'"><strong>{{label(insight.reviewState)}}</strong> by {{insight.reviewerName}}</p></ng-container><div *ngIf="recommendationError()" class="inline-error">{{recommendationError()}}</div></section></aside></div></ng-container>
  `,
  styles:[`.claim-header{display:flex;justify-content:space-between;gap:1rem;align-items:center;margin:1rem 0 1.5rem}.claim-header h1{margin:.15rem 0}.claim-header p{margin:.2rem 0;color:#637187}.eyebrow{font-size:.8rem;font-weight:800;letter-spacing:.1em;color:#287b70!important}.header-badges{display:flex;gap:.5rem}.badge{padding:.45rem .7rem;background:#e7edf5;border-radius:999px;font-weight:700}.priority{background:#fff0dc;color:#814600}.workspace{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:1rem}.main-column,aside{display:grid;gap:1rem;align-content:start}.panel{background:#fff;border:1px solid #dbe4ef;border-radius:14px;padding:1.25rem}.panel h2{margin-top:0}dl{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}dt{color:#68768a;font-size:.8rem;text-transform:uppercase}dd{margin:.2rem 0;font-weight:700}.notice{background:#fff8e8;border:1px solid #f0d499;border-radius:10px;padding:1rem}.timeline{padding-left:1.2rem}.timeline li{padding:.6rem}.timeline span,.timeline small{display:block;color:#68768a;margin-top:.2rem}.panel select{width:100%;padding:.7rem;border:1px solid #c9d5e4;border-radius:8px;margin-bottom:.75rem}.button{border:0;padding:.7rem 1rem;border-radius:8px;font-weight:700;cursor:pointer}.primary{background:#16796d;color:#fff}.danger{background:#9a3027;color:#fff}.review-actions{display:flex;gap:.5rem}.action{font-size:1.1rem;font-weight:800}.inline-error,.alert{color:#8c231a;background:#fff1f0;border:1px solid #ffb8b2;padding:.75rem;border-radius:8px;margin-top:.75rem}.empty{color:#68768a}@media(max-width:850px){.workspace{grid-template-columns:1fr}.claim-header{display:block}.header-badges{margin-top:.75rem}}`],
  changeDetection:ChangeDetectionStrategy.OnPush,
})
export class ClaimDetailPageComponent implements OnInit{
  private readonly route=inject(ActivatedRoute);private readonly api=inject(ClaimsApiService);private id='';
  readonly claim=signal<ClaimDetail|null>(null);readonly adjusters=signal<Adjuster[]>([]);readonly audit=signal<AuditEvent[]>([]);readonly recommendation=signal<Recommendation|null>(null);readonly loading=signal(true);readonly acting=signal(false);readonly pageError=signal('');readonly assignmentError=signal('');readonly statusError=signal('');readonly recommendationError=signal('');
  readonly adjusterId=new FormControl('',{nonNullable:true});readonly nextStatus=new FormControl<ClaimStatus|''>('',{nonNullable:true});
  ngOnInit():void{this.id=this.route.snapshot.paramMap.get('id')??'';forkJoin({claim:this.api.get(this.id),adjusters:this.api.getAdjusters(),audit:this.api.getAudit(this.id)}).subscribe({next:value=>{this.claim.set(value.claim);this.adjusters.set(value.adjusters);this.audit.set(value.audit);this.adjusterId.setValue(value.claim.assignedAdjuster?.id??'');this.loading.set(false);},error:(error:unknown)=>{this.pageError.set(this.message(error,'Claim workspace is unavailable.'));this.loading.set(false);}});}
  assign():void{if(!this.adjusterId.value)return;this.acting.set(true);this.assignmentError.set('');this.api.assign(this.id,this.adjusterId.value,'Interview User').subscribe({next:value=>{this.claim.set(value);this.acting.set(false);this.refreshAudit();},error:(error:unknown)=>{this.assignmentError.set(this.message(error,'Assignment failed.'));this.acting.set(false);}});}
  updateStatus():void{if(!this.nextStatus.value)return;this.acting.set(true);this.statusError.set('');this.api.updateStatus(this.id,this.nextStatus.value,'Interview User').subscribe({next:value=>{this.claim.set(value);this.nextStatus.setValue('');this.acting.set(false);this.refreshAudit();},error:(error:unknown)=>{this.statusError.set(this.message(error,'Status update failed.'));this.acting.set(false);}});}
  generate():void{this.acting.set(true);this.recommendationError.set('');this.api.generateRecommendation(this.id).subscribe({next:value=>{this.recommendation.set(value);this.acting.set(false);this.refreshAudit();},error:(error:unknown)=>{this.recommendationError.set(this.message(error,'Recommendation failed.'));this.acting.set(false);}});}
  review(decision:'APPROVED'|'REJECTED'):void{const current=this.recommendation();if(!current)return;this.acting.set(true);this.api.reviewRecommendation(this.id,current.id,decision,'Interview User').subscribe({next:value=>{this.recommendation.set(value);this.acting.set(false);this.refreshAudit();},error:(error:unknown)=>{this.recommendationError.set(this.message(error,'Review failed.'));this.acting.set(false);}});}
  label(value:string):string{return value.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());}
  private refreshAudit():void{this.api.getAudit(this.id).subscribe(value=>this.audit.set(value));}
  private message(error:unknown,fallback:string):string{return error instanceof ApiError?error.message:fallback;}
}
