import { TourStep } from './tour.models';

export const TOUR_STEPS: readonly TourStep[] = [
  {
    id: 'claimant-portal',
    index: 0,
    title: 'Claimant sees one clear next action',
    notice: 'The customer portal shows status, evidence progress, messages, and a plain-language next step without exposing internal risk logic.',
    technicalProof: 'The page reads a claimant-safe Spring projection and a filtered timeline rather than reusing the employee claim payload.',
    target: 'claimant-portal',
    route: claimId => claimId ? `/portal/claims/${claimId}` : '/portal',
  },
  {
    id: 'adjuster-review',
    index: 1,
    title: 'Adjuster keeps consequential action human',
    notice: 'Jordan Lee reviews authoritative evidence and bounded guidance before any claimant communication or recommendation review is confirmed.',
    technicalProof: 'The Angular workspace posts claimant-visible messages only after confirmation and never changes claim status implicitly.',
    target: 'decision-support',
    role: 'adjuster',
    route: claimId => claimId ? `/app/claims/${claimId}` : '/app/my-work',
  },
  {
    id: 'manager-impact',
    index: 2,
    title: 'Manager sees the operational impact',
    notice: 'The same reserved claim appears inside portfolio pressure, evidence readiness, ownership, SLA, and the live queue.',
    technicalProof: 'Manager surfaces combine the dashboard snapshot API with the exact stored claim identifier returned by the reset transaction.',
    target: 'manager-golden-journey',
    role: 'manager',
    route: () => '/app/dashboard',
  },
  {
    id: 'administrator-routing',
    index: 3,
    title: 'Administrator explains the routing',
    notice: 'The workflow builder loads the real claim as a local routing preview while save, validation, and activation boundaries remain explicit.',
    technicalProof: 'The simulator maps backend claim state into a typed local input. It cannot approve, deny, mutate, or activate a production workflow.',
    target: 'admin-routing-preview',
    role: 'admin',
    route: () => '/app/workflows',
  },
  {
    id: 'engineering-proof',
    index: 4,
    title: 'Inspect the engineering proof',
    notice: 'The journey is implemented across Angular, Spring Boot, PostgreSQL, deterministic policies, bounded assistance, and persistent audit history.',
    technicalProof: 'CI verifies backend transactions, frontend behavior, production builds, and rendered visual QA before the branch is considered complete.',
    target: 'engineering-proof',
    route: () => '/tour',
  },
];
